import React from 'react';
import {
  Search,
  Settings,
  MapPin,
  Star,
  Heart,
  MessageCircle,
  Calendar,
  Clock,
  User,
  ChevronLeft,
  ChevronRight,
  X,
  Check,
  Plus,
  Home,
  Users,
  Bookmark,
  Camera,
  Image,
  Send,
  Filter,
  Coffee,
  Utensils,
  Wine,
  Music,
  Sparkles,
  Shield,
  CreditCard,
  HelpCircle,
  AlertCircle,
  CheckCircle,
  XCircle,
  Info,
  Zap,
  Globe,
  Phone,
  Mail,
  Lock,
  Eye,
  EyeOff,
  Edit,
  Trash,
  Share,
  Download,
  Upload,
  RefreshCw,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Bell,
  BellOff,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Video,
  VideoOff,
  MoreVertical,
  MoreHorizontal,
  Menu,
  Grid,
  List,
  LogOut,
  LogIn,
  UserPlus,
  UserCheck,
  Rabbit,
  SlidersHorizontal,
  Navigation,
  Receipt,
  Cake,
  FileText,
  Film,
  Palette,
  Footprints,
  PartyPopper,
  Theater,
  type LucideIcon,
} from 'lucide-react-native';
import { colors } from '../constants/theme';

// Icon name to component mapping
const iconMap: Record<string, LucideIcon> = {
  search: Search,
  settings: Settings,
  'map-pin': MapPin,
  star: Star,
  heart: Heart,
  message: MessageCircle,
  'message-circle': MessageCircle,
  calendar: Calendar,
  clock: Clock,
  user: User,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  x: X,
  check: Check,
  plus: Plus,
  home: Home,
  users: Users,
  bookmark: Bookmark,
  camera: Camera,
  image: Image,
  send: Send,
  filter: Filter,
  coffee: Coffee,
  utensils: Utensils,
  wine: Wine,
  music: Music,
  sparkles: Sparkles,
  shield: Shield,
  'credit-card': CreditCard,
  help: HelpCircle,
  alert: AlertCircle,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  info: Info,
  zap: Zap,
  globe: Globe,
  phone: Phone,
  mail: Mail,
  lock: Lock,
  eye: Eye,
  'eye-off': EyeOff,
  edit: Edit,
  trash: Trash,
  share: Share,
  download: Download,
  upload: Upload,
  refresh: RefreshCw,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  bell: Bell,
  'bell-off': BellOff,
  volume: Volume2,
  'volume-off': VolumeX,
  mic: Mic,
  'mic-off': MicOff,
  video: Video,
  'video-off': VideoOff,
  'more-vertical': MoreVertical,
  'more-horizontal': MoreHorizontal,
  menu: Menu,
  grid: Grid,
  list: List,
  'log-out': LogOut,
  'log-in': LogIn,
  'user-plus': UserPlus,
  'user-check': UserCheck,
  rabbit: Rabbit,
  sliders: SlidersHorizontal,
  navigation: Navigation,
  receipt: Receipt,
  cake: Cake,
  'file-text': FileText,
  'help-circle': HelpCircle,
  film: Film,
  theater: Theater,
  palette: Palette,
  footprints: Footprints,
  'party-popper': PartyPopper,
  receipt: Receipt,
  cake: Cake,
  'calendar-x': Calendar,
  'building-2': Grid,
};

export interface IconProps {
  name: keyof typeof iconMap;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export function Icon({
  name,
  size = 24,
  color = colors.textSecondary,
  strokeWidth = 2,
}: IconProps) {
  const IconComponent = iconMap[name];

  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`);
    return null;
  }

  return (
    <IconComponent
      size={size}
      color={color}
      strokeWidth={strokeWidth}
    />
  );
}

export type IconName = keyof typeof iconMap;
